abandon 放棄


==========================================
= We are waiting a connection on port 5852.                                                                                                                                                                                                           =
= Microsoft Windows [版本 10.0.26200.7623]                                                                                                                                                                                                            =
= (c) Microsoft Corporation. 著作權所有，並保留一切權利。                                                                                                                                                                                             =
=                                                                                                                                                                                                                                                     =
= D:\Dropbox\12-Office-SyncMTS-Switch\12_ECS5550-30_54X_SHA\02_ECS5550-30_54X_V3.2                                                                                                                                                                    =
= .3.261.1E.12A_PKI2_SHA_260205>connection from 127.0.0.1:64653.                                                                                                                                                                                      =
= We are waiting a connection on port 5852.                                                                                                                                                                                                           =
= Microsoft Windows [版本 10.0.26200.7623]                                                                                                                                                                                                            =
= (c) Microsoft Corporation. 著作權所有，並保留一切權利。                                                                                                                                                                                             =
= D:\Dropbox\12-Office-SyncMTS-Switch\12_ECS5550-30_54X_SHA\02_ECS5550-30_54X_V3.2.3.261.1E.12A_PKI2_SHA_260205>connection from 127.0.0.1:64653.                                                                                                      =
= cd                                                                                                                                                                                                                                                  =
= D:\Dropbox\12-Office-SyncMTS-Switch\12_ECS5550-30_54X_SHA\02_ECS5550-30_54X_V3.2.3.261.1E.12A_PKI2_SHA_260205                                                                                                                                       =
= D:\Dropbox\12-Office-SyncMTS-Switch\12_ECS5550-30_54X_SHA\02_ECS5550-30_54X_V3.2.3.261.1E.12A_PKI2_SHA_260205>cd D:/Dropbox/12-Office-SyncMTS-Switch/12_ECS5550-30_54X_SHA/02_ECS5550-30_54X_V3.2.3.261.1E.12A_PKI2_SHA_260205/extapp/FTP_TFTP_AUTO =
= D:\Dropbox\12-Office-SyncMTS-Switch\12_ECS5550-30_54X_SHA\02_ECS5550-30_54X_V3.2.3.261.1E.12A_PKI2_SHA_260205\extapp\FTP_TFTP_AUTO>plink.exe -ssh 10.150.192.41                                                                                     =
= The host key is not cached for this server:                                                                                                                                                                                                         =
=   10.150.192.41 (port 22)                                                                                                                                                                                                                           =
= You have no guarantee that the server is the computer you                                                                                                                                                                                           =
= think it is.                                                                                                                                                                                                                                        =
= The server's rsa2 key fingerprint is:                                                                                                                                                                                                               =
=   ssh-rsa 2048 SHA256:8Jr/l0qEpREu3iMxbiEyeaemyJXOcXdhm6/4kx3kckw                                                                                                                                                                                   =
= If you trust this host, enter "y" to add the key to Plink's                                                                                                                                                                                         =
= cache and carry on connecting.                                                                                                                                                                                                                      =
= If you want to carry on connecting just once, without adding                                                                                                                                                                                        =
= the key to the cache, enter "n".                                                                                                                                                                                                                    =
= If you do not trust this host, press Return to abandon the                                                                                                                                                                                          =
= connection.     
