指令解釋
將含許多項目, 且內含如下的資訊, 只取除 LICENSE= 以外的內容.
LICENSE=c3ctbGljZW5zZS8xLjEKTmFtZTogRUMKQ29udGFjdDogCkxvY2F0aW9uOiAKRGVzY3JpcHRpb246IApDUFUtTUFDLUFkZHJlc3M6IEQwLTc3LUNFLTVCLUY5LUFEClByb2plY3QtTnVtYmVyOiBFQ1M0MTI1CkFjY2VwdC1Nb2RlOiBsZWdhY3kKTGljZW5zZS1OdW1iZXI6IDdkNDg4YWJlLWU4NTgtNDAzZi1iYWQ3LTBiM2I2YTVjZTJlNQpMaWNlbnNlLUlzc3VlLURhdGU6IEZyaSBBcHIgMjggMTI6MDY6MTggMjAyMwpMaWNlbnNlLVByb2ZpbGU6IEwyKywgY2xvdWQtdQpMaWNlbnNlLVByb2ZpbGUtRGlnZXN0OiBkOWM0YjU5YzEyMmIwMzg0Y2RlMDJiZDE5NDJjZmFiNgpMaWNlbnNlLUFjY2Vzcy1MaXN0OiAvdndTK1l5dXFVbzZtODROMHA3d1dUL1VpankyTVlHa05RNXJLMkxXZzE2VjNrQm5YTkZaKzFoaGZtS21pZG9ER2xWT3RTRFp4QWd0UXVWL3Z3NkpnVVNCd2VoZ0RGeSs4a1FFTUc1UEdrdnhOaGwwUm9iYmY5WVJqa0N3SnV0S0puampOQkRmcnF5L3VkSDFKaldXQ2tnbkJmaktxR0hkZ3R2NHBycUF3TXJPQ0J2bkE0K0N3ejNYTkQrcjhqcHlkcW52aEswTmEycmpOQVRiMkZibWpjUjlmQWFNRE5Tdk9WM0FXV3Vici8rZDlwa1pQeHJpTjlSUVRSLy9kdnZVZkxrOTFRTVFvVG9TM2hVQlRXNGhsZ2lrLzRqSC9GVG9KaVJyanVEMUNhaz0KU2lnbmF0dXJlMTogRDIxeDlRL0JhdGNpT21RaDNJc3Q2L2Yzais3aFhzZFZiU21UUkZyNS9nOEU5cTRzcGtXZjBVTDUvRlNyaURoVlcyQ1FibXl1TkJLUHBWOFFVRUZRWDBXNUFmTmtTYm9PVERaMXZBaW5PbmIvZXFTeDJqRDBZYzFaRkVpRENYdWhVTzRFNkY0VW9jS2RqYWkreGxKaldqR0MxU21wVklFd2VzT2w0eUhtZXBOUWVVYkJPdTdOTHM5Q3Y0Rk9UVDFoTUQ5cUxpMUIrY1FCclZITEUweDZVNnA5YjhqRFpVeTRVSUtheWZaOTJoWk95Y0J5YnFXQytCdGllUzhWWHBCUVM5OXlFOU5HM1FUMHg2Z2RHbHh2c0tJdHByWWJSazZ1aCsvYStNTENCTU4zOEthUU9ZSEZqL1RkUTRMdkhmVTRzdE9IdnFOZmw0ZXpCS2FIWnFKcXZnPT0KU2lnbmF0dXJlMjogTWVGKytKVGJVcWhheFJMSjd0YkRsV2MrMXF1ajRoM2lhVWxhZk54VVk0ZnNwZk9tWXJZSE5tcVk4K29ZalAwOW1wS0RNc081SjFrNGpxL2VSY09DMUxwYWMxajAwZk85bDJKN3dHQTdhcUNPNzE4MDQ3TDFzU1M2dHRLSVAzaG9EWm9zUmIxczczU21vNVYrWmoxZ3d0ZUwvQ2lrRk5pUnQyMjFuSVNkQitsdklVTlFLMDlhU2dkdGRucXl3Q1djbDVxcGQ2QkFYWkd6c01vL20yUVI4ZmRLUDdDQXBVWHBrM0dIVm1rQXUwbTZNUHZqaExIcWs4SDRZWEpRMTROcWxQQkkxSkhTNlVBUUwxajNuWUJuN3RuR2pQMXZwMFdMejRBWHZrQnRCakNaN0VZMjlYZUhBQmY4ZmtGNVptbWJlVU9hWWxlVmREMHp0dmZzMlk2SGhBPT0K #

取出
c3ctbGljZW5zZS8xLjEKTmFtZTogRUMKQ29udGFjdDogCkxvY2F0aW9uOiAKRGVzY3JpcHRpb246IApDUFUtTUFDLUFkZHJlc3M6IEQwLTc3LUNFLTVCLUY5LUFEClByb2plY3QtTnVtYmVyOiBFQ1M0MTI1CkFjY2VwdC1Nb2RlOiBsZWdhY3kKTGljZW5zZS1OdW1iZXI6IDdkNDg4YWJlLWU4NTgtNDAzZi1iYWQ3LTBiM2I2YTVjZTJlNQpMaWNlbnNlLUlzc3VlLURhdGU6IEZyaSBBcHIgMjggMTI6MDY6MTggMjAyMwpMaWNlbnNlLVByb2ZpbGU6IEwyKywgY2xvdWQtdQpMaWNlbnNlLVByb2ZpbGUtRGlnZXN0OiBkOWM0YjU5YzEyMmIwMzg0Y2RlMDJiZDE5NDJjZmFiNgpMaWNlbnNlLUFjY2Vzcy1MaXN0OiAvdndTK1l5dXFVbzZtODROMHA3d1dUL1VpankyTVlHa05RNXJLMkxXZzE2VjNrQm5YTkZaKzFoaGZtS21pZG9ER2xWT3RTRFp4QWd0UXVWL3Z3NkpnVVNCd2VoZ0RGeSs4a1FFTUc1UEdrdnhOaGwwUm9iYmY5WVJqa0N3SnV0S0puampOQkRmcnF5L3VkSDFKaldXQ2tnbkJmaktxR0hkZ3R2NHBycUF3TXJPQ0J2bkE0K0N3ejNYTkQrcjhqcHlkcW52aEswTmEycmpOQVRiMkZibWpjUjlmQWFNRE5Tdk9WM0FXV3Vici8rZDlwa1pQeHJpTjlSUVRSLy9kdnZVZkxrOTFRTVFvVG9TM2hVQlRXNGhsZ2lrLzRqSC9GVG9KaVJyanVEMUNhaz0KU2lnbmF0dXJlMTogRDIxeDlRL0JhdGNpT21RaDNJc3Q2L2Yzais3aFhzZFZiU21UUkZyNS9nOEU5cTRzcGtXZjBVTDUvRlNyaURoVlcyQ1FibXl1TkJLUHBWOFFVRUZRWDBXNUFmTmtTYm9PVERaMXZBaW5PbmIvZXFTeDJqRDBZYzFaRkVpRENYdWhVTzRFNkY0VW9jS2RqYWkreGxKaldqR0MxU21wVklFd2VzT2w0eUhtZXBOUWVVYkJPdTdOTHM5Q3Y0Rk9UVDFoTUQ5cUxpMUIrY1FCclZITEUweDZVNnA5YjhqRFpVeTRVSUtheWZaOTJoWk95Y0J5YnFXQytCdGllUzhWWHBCUVM5OXlFOU5HM1FUMHg2Z2RHbHh2c0tJdHByWWJSazZ1aCsvYStNTENCTU4zOEthUU9ZSEZqL1RkUTRMdkhmVTRzdE9IdnFOZmw0ZXpCS2FIWnFKcXZnPT0KU2lnbmF0dXJlMjogTWVGKytKVGJVcWhheFJMSjd0YkRsV2MrMXF1ajRoM2lhVWxhZk54VVk0ZnNwZk9tWXJZSE5tcVk4K29ZalAwOW1wS0RNc081SjFrNGpxL2VSY09DMUxwYWMxajAwZk85bDJKN3dHQTdhcUNPNzE4MDQ3TDFzU1M2dHRLSVAzaG9EWm9zUmIxczczU21vNVYrWmoxZ3d0ZUwvQ2lrRk5pUnQyMjFuSVNkQitsdklVTlFLMDlhU2dkdGRucXl3Q1djbDVxcGQ2QkFYWkd6c01vL20yUVI4ZmRLUDdDQXBVWHBrM0dIVm1rQXUwbTZNUHZqaExIcWs4SDRZWEpRMTROcWxQQkkxSkhTNlVBUUwxajNuWUJuN3RuR2pQMXZwMFdMejRBWHZrQnRCakNaN0VZMjlYZUhBQmY4ZmtGNVptbWJlVU9hWWxlVmREMHp0dmZzMlk2SGhBPT0K #

## =================================================
license 所在檔案路徑
{::ASPECTPATH}other/license_example.txt]

檔案內容, 在最下方

set licExample [_f_ReadFile ${::ASPECTPATH}other/license_example.txt]
regexp -linestop {LICENSE=(.*)} $licExample -> lic_data

set lic_data

輸出: (LICENSE= 沒被包含在內)
c3ctbGljZW5zZS8xLjEKTmFtZTogRUMKQ29udGFjdDogCkxvY2F0aW9uOiAKRGVzY3JpcHRpb246IApDUFUtTUFDLUFkZHJlc3M6IEQwLTc3LUNFLTVCLUY5LUFEClByb2plY3QtTnVtYmVyOiBFQ1M0MTI1CkFjY2VwdC1Nb2RlOiBsZWdhY3kKTGljZW5zZS1OdW1iZXI6IDdkNDg4YWJlLWU4NTgtNDAzZi1iYWQ3LTBiM2I2YTVjZTJlNQpMaWNlbnNlLUlzc3VlLURhdGU6IEZyaSBBcHIgMjggMTI6MDY6MTggMjAyMwpMaWNlbnNlLVByb2ZpbGU6IEwyKywgY2xvdWQtdQpMaWNlbnNlLVByb2ZpbGUtRGlnZXN0OiBkOWM0YjU5YzEyMmIwMzg0Y2RlMDJiZDE5NDJjZmFiNgpMaWNlbnNlLUFjY2Vzcy1MaXN0OiAvdndTK1l5dXFVbzZtODROMHA3d1dUL1VpankyTVlHa05RNXJLMkxXZzE2VjNrQm5YTkZaKzFoaGZtS21pZG9ER2xWT3RTRFp4QWd0UXVWL3Z3NkpnVVNCd2VoZ0RGeSs4a1FFTUc1UEdrdnhOaGwwUm9iYmY5WVJqa0N3SnV0S0puampOQkRmcnF5L3VkSDFKaldXQ2tnbkJmaktxR0hkZ3R2NHBycUF3TXJPQ0J2bkE0K0N3ejNYTkQrcjhqcHlkcW52aEswTmEycmpOQVRiMkZibWpjUjlmQWFNRE5Tdk9WM0FXV3Vici8rZDlwa1pQeHJpTjlSUVRSLy9kdnZVZkxrOTFRTVFvVG9TM2hVQlRXNGhsZ2lrLzRqSC9GVG9KaVJyanVEMUNhaz0KU2lnbmF0dXJlMTogRDIxeDlRL0JhdGNpT21RaDNJc3Q2L2Yzais3aFhzZFZiU21UUkZyNS9nOEU5cTRzcGtXZjBVTDUvRlNyaURoVlcyQ1FibXl1TkJLUHBWOFFVRUZRWDBXNUFmTmtTYm9PVERaMXZBaW5PbmIvZXFTeDJqRDBZYzFaRkVpRENYdWhVTzRFNkY0VW9jS2RqYWkreGxKaldqR0MxU21wVklFd2VzT2w0eUhtZXBOUWVVYkJPdTdOTHM5Q3Y0Rk9UVDFoTUQ5cUxpMUIrY1FCclZITEUweDZVNnA5YjhqRFpVeTRVSUtheWZaOTJoWk95Y0J5YnFXQytCdGllUzhWWHBCUVM5OXlFOU5HM1FUMHg2Z2RHbHh2c0tJdHByWWJSazZ1aCsvYStNTENCTU4zOEthUU9ZSEZqL1RkUTRMdkhmVTRzdE9IdnFOZmw0ZXpCS2FIWnFKcXZnPT0KU2lnbmF0dXJlMjogTWVGKytKVGJVcWhheFJMSjd0YkRsV2MrMXF1ajRoM2lhVWxhZk54VVk0ZnNwZk9tWXJZSE5tcVk4K29ZalAwOW1wS0RNc081SjFrNGpxL2VSY09DMUxwYWMxajAwZk85bDJKN3dHQTdhcUNPNzE4MDQ3TDFzU1M2dHRLSVAzaG9EWm9zUmIxczczU21vNVYrWmoxZ3d0ZUwvQ2lrRk5pUnQyMjFuSVNkQitsdklVTlFLMDlhU2dkdGRucXl3Q1djbDVxcGQ2QkFYWkd6c01vL20yUVI4ZmRLUDdDQXBVWHBrM0dIVm1rQXUwbTZNUHZqaExIcWs4SDRZWEpRMTROcWxQQkkxSkhTNlVBUUwxajNuWUJuN3RuR2pQMXZwMFdMejRBWHZrQnRCakNaN0VZMjlYZUhBQmY4ZmtGNVptbWJlVU9hWWxlVmREMHp0dmZzMlk2SGhBPT0K


############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
<time:20:21:09> [SyncData]
TYPE=Check-In
DunsNo=0001
MFGSITE=ACCTON,PASS
SIM=OFF
GUID=a2511c38-b176-4d83-a5fe-f97a9a0eec9d
UID=a2511c38-b176-4d83-a5fe-f97a9a0eec9d
LICENSE=c3ctbGljZW5zZS8xLjEKTmFtZTogRUMKQ29udGFjdDogCkxvY2F0aW9uOiAKRGVzY3JpcHRpb246IApDUFUtTUFDLUFkZHJlc3M6IEQwLTc3LUNFLTVCLUY5LUFEClByb2plY3QtTnVtYmVyOiBFQ1M0MTI1CkFjY2VwdC1Nb2RlOiBsZWdhY3kKTGljZW5zZS1OdW1iZXI6IDdkNDg4YWJlLWU4NTgtNDAzZi1iYWQ3LTBiM2I2YTVjZTJlNQpMaWNlbnNlLUlzc3VlLURhdGU6IEZyaSBBcHIgMjggMTI6MDY6MTggMjAyMwpMaWNlbnNlLVByb2ZpbGU6IEwyKywgY2xvdWQtdQpMaWNlbnNlLVByb2ZpbGUtRGlnZXN0OiBkOWM0YjU5YzEyMmIwMzg0Y2RlMDJiZDE5NDJjZmFiNgpMaWNlbnNlLUFjY2Vzcy1MaXN0OiAvdndTK1l5dXFVbzZtODROMHA3d1dUL1VpankyTVlHa05RNXJLMkxXZzE2VjNrQm5YTkZaKzFoaGZtS21pZG9ER2xWT3RTRFp4QWd0UXVWL3Z3NkpnVVNCd2VoZ0RGeSs4a1FFTUc1UEdrdnhOaGwwUm9iYmY5WVJqa0N3SnV0S0puampOQkRmcnF5L3VkSDFKaldXQ2tnbkJmaktxR0hkZ3R2NHBycUF3TXJPQ0J2bkE0K0N3ejNYTkQrcjhqcHlkcW52aEswTmEycmpOQVRiMkZibWpjUjlmQWFNRE5Tdk9WM0FXV3Vici8rZDlwa1pQeHJpTjlSUVRSLy9kdnZVZkxrOTFRTVFvVG9TM2hVQlRXNGhsZ2lrLzRqSC9GVG9KaVJyanVEMUNhaz0KU2lnbmF0dXJlMTogRDIxeDlRL0JhdGNpT21RaDNJc3Q2L2Yzais3aFhzZFZiU21UUkZyNS9nOEU5cTRzcGtXZjBVTDUvRlNyaURoVlcyQ1FibXl1TkJLUHBWOFFVRUZRWDBXNUFmTmtTYm9PVERaMXZBaW5PbmIvZXFTeDJqRDBZYzFaRkVpRENYdWhVTzRFNkY0VW9jS2RqYWkreGxKaldqR0MxU21wVklFd2VzT2w0eUhtZXBOUWVVYkJPdTdOTHM5Q3Y0Rk9UVDFoTUQ5cUxpMUIrY1FCclZITEUweDZVNnA5YjhqRFpVeTRVSUtheWZaOTJoWk95Y0J5YnFXQytCdGllUzhWWHBCUVM5OXlFOU5HM1FUMHg2Z2RHbHh2c0tJdHByWWJSazZ1aCsvYStNTENCTU4zOEthUU9ZSEZqL1RkUTRMdkhmVTRzdE9IdnFOZmw0ZXpCS2FIWnFKcXZnPT0KU2lnbmF0dXJlMjogTWVGKytKVGJVcWhheFJMSjd0YkRsV2MrMXF1ajRoM2lhVWxhZk54VVk0ZnNwZk9tWXJZSE5tcVk4K29ZalAwOW1wS0RNc081SjFrNGpxL2VSY09DMUxwYWMxajAwZk85bDJKN3dHQTdhcUNPNzE4MDQ3TDFzU1M2dHRLSVAzaG9EWm9zUmIxczczU21vNVYrWmoxZ3d0ZUwvQ2lrRk5pUnQyMjFuSVNkQitsdklVTlFLMDlhU2dkdGRucXl3Q1djbDVxcGQ2QkFYWkd6c01vL20yUVI4ZmRLUDdDQXBVWHBrM0dIVm1rQXUwbTZNUHZqaExIcWs4SDRZWEpRMTROcWxQQkkxSkhTNlVBUUwxajNuWUJuN3RuR2pQMXZwMFdMejRBWHZrQnRCakNaN0VZMjlYZUhBQmY4ZmtGNVptbWJlVU9hWWxlVmREMHp0dmZzMlk2SGhBPT0K
[CheckIn]
SN=EC2317005534,PASS
MAC_START=D077CE5BF9AD,PASS
PN=C0PEC4310401Z,PASS
OP=A1000333,PASS
WSID=FT-GL,PASS
LINE=Z5-L3PU,PASS
RACK_ID=FT-GL
TEST_PC=FT-GL
TEST_PC_IP=10.2.78.122
TPVER=V1.1.0.12.1E1.06,PASS,PASS
FWVER=1.1.0.12
FORCECHECK=1
TIMESYNC=20230428202106
ROUTE_ID=27abb247-09ff-4f76-8b04-0e246149c450
PROJECTNAME=ECS4100
LICENSETYPE=regular
USERNAME=EC
USERCONTACT=
USERLOCATION=
USERDESCRIPTION=
SWVER=1.2.77.212
SOFTWAREMODE=legacy
VALIDITYSTARTDATE=2023-04-28 20:21:06
VALIDITYENDDATE=2033-04-25 20:21:06
SERVER_TIME=20230428202107
STATUS=PASS
[TestLog]
STATUS=PASS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #
############################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################
